services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./php:/usr/src/myapp
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: shops
      DB_USER: admin
      DB_PASS: admin

  postgres:
    image: postgres
    container_name: database
    volumes:
      - ./sql/init/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: shops
    ports:
      - 5432:5432
